### ISSUE TITLE
SHA512 Test

### ISSUE THREAD

**Issue by JlnWntr** [user-none/lua-hashings#2]
A sha512-hash generated by openssl:

`$ openssl dgst -sha512 <<< "Test" 
ffb360b65e823271ec9dc554a984bcb41793cbb91cba641c52a56b29d1d5dc5f219ad18fe03fd1eb6005da7d88af158369891115f1d6dbcfa0a23b8096b64a47`

is different to the one generated by lua-hashings:

`local Digest = require("sha512");
local test = Digest:new("Test"):hexdigest();
print(test)`
`(C6EE9E33CF5C6715A1D148FD73F7318884B41ADCB916021E2BC0E800A5C5DD97F5142178F6AE88C8FDD98E1AFB0CE4C8D2C54B5F37B30B7DA1997BB33B0B8A31)`

**Comment by user-none** [comment]
The issue is how you're feeding the data to OpenSSL.

`<<<` add a new line to the end of the input which is being used as part of the hashed data.

You can see this is what's happening by using echo and piping in the data.

    $ echo "Test" | openssl dgst -sha512
    ffb360b65e823271ec9dc554a984bcb41793cbb91cba641c52a56b29d1d5dc5f219ad18fe03fd1eb6005da7d88af158369891115f1d6dbcfa0a23b8096b64a47

Now if you use `-n` to tell `echo` not to add the new line you get the same as hashings.

    $ echo -n "Test" | openssl dgst -sha512
    c6ee9e33cf5c6715a1d148fd73f7318884b41adcb916021e2bc0e800a5c5dd97f5142178f6ae88c8fdd98e1afb0ce4c8d2c54b5f37b30b7da1997bb33b0b8a31

You can further verify this by adding a `\n` to the input in your test code. In which case you'll get the `ff...` output.

    local Digest = require("sha512"); local test = Digest:new("Test\n"):hexdigest(); print(test)
    FFB360B65E823271EC9DC554A984BCB41793CBB91CBA641C52A56B29D1D5DC5F219AD18FE03FD1EB6005DA7D88AF158369891115F1D6DBCFA0A23B8096B64A47

**Comment by JlnWntr** [comment]
Thank you so much!!
