### ISSUE TITLE
Hmac SHA512 not working on EXMO

### ISSUE THREAD

**Issue by barmaley997** [user-none/lua-hashings#8]
Hello again, so now i've tried to apply this hashing methods - Hmac and SHA512 to work with the authenticated API access my account on EXMO,  [https://exmo.me/en/api](url)  it seems i've done all right, but it is not working at all - EXMO server always gives me error:

>  1
> 200
> connection	close
> access-control-allow-headers	Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Key, Sign
> content-type	application/json; charset=utf-8
> strict-transport-security	max-age=604800
> content-length	81
> server	nginx
> access-control-allow-credentials	true
> access-control-allow-methods	POST, GET, OPTIONS, PUT, DELETE
> date	Sun, 20 Oct 2019 09:48:24 GMT
> Response body:
> {"result":false,"error":"Error 40005: Authorization error, Incorrect signature"}

So my code looks like this:

```
ssl = require("ssl")
http = require("socket.http")
https = require("ssl.https")
socket = require("socket")
ltn12 = require("ltn12")
hashings = require("hashings")

api_key = "myopenkey"
api_secret = "mysecretkey"

x = tostring(math.modf(os.time()*1000))

hs = hashings.hmac(hashings.sha512, api_secret)
hs:update(x)
sign=hs:hexdigest()

local request_body = "nonce="..tostring(x)
local response_body = {}

local res, code, response_headers = https.request{
    url = "https://api.exmo.com/v1/user_info/",
    method = "POST", 
    headers = 
      {
          ["Content-Type"] = "application/x-www-form-urlencoded",
          ["Content-Length"] = #request_body,
		   Key=api_key,
		   Sign=sign
      },
      source = ltn12.source.string(request_body),
      sink = ltn12.sink.table(response_body),
}

print(res)
print(code)

if type(response_headers) == "table" then
  for k, v in pairs(response_headers) do 
    print(k, v)
  end
end

print("Response body:")
if type(response_body) == "table" then
  print(table.concat(response_body))
else
  print("Not a table:", type(response_body))
end
```

EXMO posted examples to access their API on many languages - 
[https://github.com/exmo-dev/exmo_api_lib](url)
I've tried their example on python2:

```
import httplib
import urllib
import json
import hashlib
import hmac
import time
 
api_key = "your_key"
api_secret = "your_secret"

nonce = int(round(time.time()*1000))
 
params = {"nonce": nonce}
params = urllib.urlencode(params)
 
H = hmac.new(api_secret, digestmod=hashlib.sha512)
H.update(params)
sign = H.hexdigest()
 
headers = {"Content-type": "application/x-www-form-urlencoded",
           "Key":api_key,
           "Sign":sign}
conn = httplib.HTTPSConnection("api.exmo.com")
conn.request("POST", "/v1/user_info", params, headers)
response = conn.getresponse()
 
print response.status, response.reason
print json.load(response)
 
conn.close()
```

 and python3 also, and it was working without any problem - no any error messages and quick access to account
So it seems that one of your algorithms - Hmac or SHA-512, or both, has some differences from implementation of this algorithms in many languages

**Comment by user-none** [comment]
You're calculating the HMAC using different data types. Lua you're using the nonce as a string as the data. In Python you're using a dict with a string key and integer value as the data. You need to work with EXMO to determine exactly how the payload data needs to represented when passed to the hashing library.

**Comment by barmaley997** [comment]
> Lua you're using the nonce as a string as the data. In Python you're using a dict with a string key and integer value as the data

Yes!  I overlooked this! I passed nonce to update() in lua code immediately after calculating it as a numeric value converted to string:
x = tostring(math.modf(os.time()*1000))
hs = hashings.hmac(hashings.sha512, api_secret)
hs:update(x)

So the x is the numeric string like as '3453345345'

but in Pyhton code nonce, after calculating its value and converting into string, concatenating with the string "nonce=" so the final string that passed to update() looks like this:
"nonce=3453345345"
So i fix this in Lua code to:

params = "nonce="..tostring(math.modf(os.time()*10000))
hs = hashings.hmac(hashings.sha512, api_secret)
hs:update(params)

But it not worked at once, one else thing was need to fix:
in python string sign was exist only from lower-case symbols like this:
e998231bbf544c09de83a1a738febfa64351d91c58067905cbac23dc18f3892541ebee57d08521095bfff10644276b26b9e2a5d3376fbcb0c3fe6d474ad54439
but your function hexdigest()  returns always upper-case symbols,
so i fixed this by:
sign=string.lower(hs:hexdigest())
and after that it worked! I accesed to my EXMO account!!!!


But one else question: why calculation  of HMAC SHA512 in your lua-hashings library is so slow?
it takes about several minutes, but in python, on the same computer, this algorith calculated almost at once, calculation takes about several seconds.
Why is such difference?

**Comment by user-none** [comment]
> But one else question: why calculation of HMAC SHA512 in your lua-hashings library is so slow?
> it takes about several minutes, but in python, on the same computer, this algorith calculated almost at once, calculation takes about several seconds.
> Why is such difference?

Python's crypto operations are native code and are written in C, which makes them much faster. My library is pure Lua which is why it's so much slower.

**Reason 1**: Most crypto algorithms rely on fixed size unsigned integer wrapping behavior and Lua only has 1 size integer, signed 64 bit (default but can be compiled with different sizes). lua-num (also my library) which is also a pure Lua library is used to emulate fixed size integers of various sizes and integer wrapping. Emulating this behavior is slow.

Unsigned 64 bit integers is the slowest because no native code like optimizations are available. Integer wrapping for an unsigned 32 bit integer can be emulated using Lua's 64 bit integer. The integer itself and operations like bit shifting is fast because it's the native type.

An unsigned 64 bit integer with wrapping support cannot be contained in a singed 64 bit integer. lua-nums needs to use the big num type underneath which makes calculations very slow. Native operations like bit shifting isn't available and needs to additionally be emulated.

You called out SHA512 which uses unsigned 64 bit integers. Making SHA512 a very slow algorithm in pure Lua. If you used SHA256 it would be faster. But still slow because emulation of integer wrapping is still required.

Python's crypto written in C doesn't have do this emulation.

**Rason 2**: C compilers are able to detect and optimize many crypto operations and some processors have acceleration for certain crypto. For example, x64 processors have the aes-ni instructions which further accelerates AES encryption. Anything written in Lua isn't able to take advantage of processor level optimizations. Python's C crypto code being compiled can benefit from compiler optimizations.

**Making it faster**: A Lua crypto wrapper around something like OpenSSL would calculate a HMAC SHA512 almost instantly because the Lua code is calling an optimized C library. However, lua-hashings was written in pure Lua so C libraries are not needed. It's portable to any system that runs Lua because no native code needs to be compiled. There is no worry about X library working or not working or needing to be installed on the system for this library to work.

**Comment by barmaley997** [comment]
I guess about it, much thanks for your reply and your great work! ))
